  
name: Test Workflows

on:
  push:
    branches:
      - master
  release:
    types: 
      - published

jobs:
  container-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump GitHub context
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      
      - name: Use previous env
        run: echo "$GITHUB_EVENT"
